# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: '#home'
    weight: 10
  - name: Partners
    url: 'partners'
    weight: 20
  - name: Blog
    url: 'post'
    weight: 30
  - name: Demo
    url: 'demo'
    weight: 40
  - name: Contact
    url: 'feedback'
    weight: 50
  - name: About
    identifier: about-main
    url: 'about'
    weight: 60
  - parent: about-main
    indentifier: about-team
    name: Our team
    url: 'about'
    weight: 1
  - parent: about-main
    indentifier: about-foundation
    name: Contact details
    url: 'about#details'
    weight: 2
  - parent: about-main
    indentifier: about-privacy
    name: Privacy
    url: 'privacy'
    weight: 3
  - parent: about-main
    indentifier: about-security
    name: Security
    url: 'security'
    weight: 4
  - parent: about-main
    indentifier: about-support
    name: Support
    url: 'support'
    weight: 5
  - name: 
    pre: <i class="fab fa-github"></i>
    post: 
    url: 'https://github.com/alkem-io'
    weight: 70


# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/uploads/resume.pdf` and uncomment the lines below.
#  - name: CV
#    url: uploads/resume.pdf
#    weight: 70
