############# English navigation ##############

# main menu

[[main]]
name = "Home"
pageRef = "/"
weight = 1

[[main]]
name = "About"
pageRef = "/about"
weight = 2

# [[main]]
# name = "Contribute"
# url = "/contribute"
# weight = 3

[[main]]
name = "Visit Platform"
url = "https://www.alkem.io"
weight = 4

# footer menu
# [[footer_01]]
# name = "Feature"
# url = "/feature"
# weight = 1

# [[footer_01]]
# name = "Pricing"
# url = "/pricing"
# weight = 2

[[footer_01]]
name = "Blogs"
url = "/blog"
weight = 1

[[footer_01]]
name = "Newsletter"
url = "https://welcome.alkem.io/newsletter"
params = { target = "_blank" }
weight = 2

[[footer_01]]
name = "Privacy Policy"
url = "/privacy-policy"
weight = 3

# [[footer_01]]
# name = "Support"
# url = "/support"
# weight = 3
