# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: '#home'
    weight: 10
  - name: Vision
    url: 'vision'
    weight: 15
  - name: Partners
    url: 'partners'
    weight: 20
  #- name: Blog
  #  url: 'post'
  #  weight: 30
  - name: Platform
    url: 'https://hub.alkem.io'
    weight: 40
  - name: About
    identifier: about-main
    url: 'about'
    weight: 60
  - parent: about-main
    indentifier: about-team
    name: Our team
    url: 'about'
    weight: 1
  - parent: about-main
    indentifier: about-foundation
    name: Contact
    url: 'feedback'
    weight: 2
  - parent: about-main
    indentifier: about-support
    name: Support
    url: 'support'
    weight: 5



# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/uploads/resume.pdf` and uncomment the lines below.
#  - name: CV
#    url: uploads/resume.pdf
#    weight: 70
