# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: '#home'
    weight: 10
  - name: Manifesto
    url: 'manifesto'
    weight: 15
  - name: Partners
    url: 'partners'
    weight: 20
  - name: News
    url: 'news'
    weight: 30
  - name: About
    identifier: about-main
    url: 'about'
    weight: 40
  - parent: about-main
    indentifier: about-team
    name: Our team
    url: 'about'
    weight: 1
  - parent: about-main
    indentifier: about-foundation
    name: Contact
    url: 'feedback'
    weight: 2
  - parent: about-main
    indentifier: about-support
    name: Support
    url: 'help'
    weight: 5
  - parent: about-main
    indentifier: about-vision
    name: Vision
    url: 'vision'
    weight: 8
  - parent: about-main
    indentifier: about-faq
    name: FAQ
    url: 'faq'
    weight: 9

main_right:
  - name: <b>Visit the platform</b>
    url: 'https://alkem.io'
    weight: 60

