[build]
  command = "hugo --gc --minify -b $URL"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.140.2"
  GO_VERSION = "1.21"

[context.production.environment]
  HUGO_ENV = "production"

[context.deploy-preview]
  command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[[redirects]]
  from = "/post/2023-04-innovation-library/"
  to = "https://welcome.alkem.io/blog/2023-04-innovation-library/"
  status = 301
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Report-To = "{\"group\":\"default\",\"max_age\":31536000,\"endpoints\":[{\"url\":\"https://alkemio.report-uri.com/a/d/g\"}],\"include_subdomains\":true}"
    Content-Security-Policy = """
        default-src 'self' https://cdn.jsdelivr.net https://cdnjs.cloudflare.com https://netlify.com https://*.netlify.com \
        style-src 'self' 'unsafe-hashes' 'unsafe-inline' https://*.alkemio.org https://*.alkemio.foundation \
          https://cdn.jsdelivr.net https://cdnjs.cloudflare.com https://*.netlify.app https://api.fontshare.com; \
        script-src 'self' 'unsafe-hashes' 'unsafe-inline' 'unsafe-eval' https://*.netlify.com https://cdn.segment.com \
          https://unpkg.com https://cdn.jsdelivr.net https://*.netlify.app; \
        font-src 'self' https://cdnjs.cloudflare.com https://api.fontshare.com https://use.fontawesome.com data:; \
        connect-src 'self' https://cdn.segment.com https://www.netlifystatus.com; \
        img-src 'self' blob: data: https:; \
        form-action 'self'; \
        base-uri 'self'; \
        report-uri https://alkemio.report-uri.com/r/d/csp/enforce; \
        """
