[build]
  command = "hugo --gc --minify -b $URL"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.119.0"
  HUGO_ENABLEGITINFO = "false"
  GO_VERSION = "1.19"

[context.production.environment]
  HUGO_ENV = "production"

[context.deploy-preview]
  command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[[plugins]]
  package = "netlify-plugin-hugo-cache-resources"
  [plugins.inputs]
    debug = true

[[redirects]]
  from = "/post/2023-04-innovation-library/"
  to = "https://welcome.alkem.io/blog/2023-04-innovation-library/"
  status = 301
  force = true

[[redirects]]
  from = "/post/2021-07-public-preview/"
  to = "https://welcome.alkem.io/blog/2021-07-public-preview/"
  status = 301
  force = true

[[redirects]]
  from = "/post/2021-07-public-preview-video/"
  to = "https://welcome.alkem.io/blog/2021-07-public-preview-video/"
  status = 301
  force = true

[[redirects]]
  from = "/post/2021-09-essif-lab/"
  to = "https://welcome.alkem.io/blog/2021-09-essif-lab/"
  status = 301
  force = true

[[redirects]]
  from = "/post/2021-09-code-for-all/"
  to = "https://welcome.alkem.io/blog/2021-09-code-for-all/"
  status = 301
  force = true

[[redirects]]
  from = "/post/2021-10-code4all-event/"
  to = "https://welcome.alkem.io/blog/2021-10-code4all-event/"
  status = 301
  force = true

[[redirects]]
  from = "/post/2021-10-interview-merijn/"
  to = "https://welcome.alkem.io/blog/2021-10-interview-merijn/"
  status = 301
  force = true

[[redirects]]
  from = "/post/2021-10-impactfest/"
  to = "https://welcome.alkem.io/blog/2021-10-impactfest/"
  status = 301
  force = true

[[redirects]]
  from = "/post/2021-11-interview-flori/"
  to = "https://welcome.alkem.io/blog/2021-11-interview-flori/"
  status = 301
  force = true

# Note: "2021-11-webinar" link missing on foundation site

[[redirects]]
  from = "/post/2021-12-webinar2/"
  to = "https://welcome.alkem.io/blog/2021-12-webinar2/"
  status = 301
  force = true

[[redirects]]
  from = "/post/2022-02-canvases/"
  to = "https://welcome.alkem.io/blog/2022-02-canvases/"
  status = 301
  force = true

[[redirects]]
  from = "/post/2022-03-uwv/"
  to = "https://welcome.alkem.io/blog/2022-03-uwv/"
  status = 301
  force = true

[[redirects]]
  from = "/post/2022-04-community/"
  to = "https://welcome.alkem.io/blog/2022-04-community/"
  status = 301
  force = true

[[redirects]]
  from = "/post/2022-04-translation-uwv/"
  to = "https://welcome.alkem.io/blog/2022-04-translation-uwv/"
  status = 301
  force = true

[[redirects]]
  from = "/post/2022-05-wisdom/"
  to = "https://welcome.alkem.io/blog/2022-05-wisdom/"
  status = 301
  force = true

[[redirects]]
  from = "/post/2022-05-webbers/"
  to = "https://welcome.alkem.io/blog/2022-05-webbers/"
  status = 301
  force = true

[[redirects]]
  from = "/post/2022-06-23-riconline/"
  to = "https://welcome.alkem.io/blog/2022-06-23-riconline/"
  status = 301
  force = true

[[redirects]]
  from = "/post/2022-06-29-home-page/"
  to = "https://welcome.alkem.io/blog/2022-06-29-home-page/"
  status = 301
  force = true

[[redirects]]
  from = "/post/2022-07-spreadsheet/"
  to = "https://welcome.alkem.io/blog/2022-07-spreadsheet/"
  status = 301
  force = true

[[redirects]]
  from = "/post/2022-08-knowledgebase/"
  to = "https://welcome.alkem.io/blog/2022-08-knowledgebase/"
  status = 301
  force = true

[[redirects]]
  from = "/post/2022-09-callouts/"
  to = "https://welcome.alkem.io/blog/2022-09-callouts/"
  status = 301
  force = true

[[redirects]]
  from = "/post/2022-09-ux-refresh/"
  to = "https://welcome.alkem.io/blog/2022-09-ux-refresh/"
  status = 301
  force = true

[[redirects]]
  from = "/post/2022-10-translations/"
  to = "https://welcome.alkem.io/blog/2022-10-translations/"
  status = 301
  force = true

[[redirects]]
  from = "/post/2022-12-key-concepts/"
  to = "https://welcome.alkem.io/blog/2022-12-key-concepts/"
  status = 301
  force = true

[[redirects]]
  from = "/post/2022-12-ui-refresh/"
  to = "https://welcome.alkem.io/blog/2022-12-ui-refresh/"
  status = 301
  force = true

[[redirects]]
  from = "/post/2023-04-innovation-library/"
  to = "https://welcome.alkem.io/blog/2023-04-innovation-library/"
  status = 301
  force = true

[[redirects]]
  from = "/post/2023-04-alkemio-spaces/"
  to = "https://welcome.alkem.io/blog/2023-04-alkemio-spaces/"
  status = 301
  force = true

[[redirects]]
  from = "/post/2023-05-changenow-event/"
  to = "https://welcome.alkem.io/blog/2023-05-changenow-event/"
  status = 301
  force = true

[[redirects]]
  from = "/post/2023-05-changenow-reflection/"
  to = "https://welcome.alkem.io/blog/2023-05-changenow-reflection/"
  status = 301
  force = true

[[redirects]]
  from = "/post/2023-08-velolab-introduction/"
  to = "https://welcome.alkem.io/blog/2023-08-velolab-introduction/"
  status = 301
  force = true

[[redirects]]
  from = "/post/2023-08-digital-twin-introduction/"
  to = "https://welcome.alkem.io/blog/2023-08-digital-twin-introduction/"
  status = 301
  force = true

[[redirects]]
  from = "/post/2023-10-urban-sensing-lab/"
  to = "https://welcome.alkem.io/blog/2023-10-urban-sensing-lab/"
  status = 301
  force = true


[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Report-To = "{\"group\":\"default\",\"max_age\":31536000,\"endpoints\":[{\"url\":\"https://alkemio.report-uri.com/a/d/g\"}],\"include_subdomains\":true}"
    Content-Security-Policy = """
        default-src 'self' https://cdn.jsdelivr.net https://fonts.googleapis.com https://fonts.gstatic.com https://netlify.com https://*.netlify.com \
          https://syndication.twitter.com https://platform.twitter.com https://*.hs-analytics.com https://*.hs-banner.com https://*.hs-scripts.com \
          https://*.hscollectedforms.net https://*.hsforms.net https://*.hsforms.com https://*.vimeo.com https://vimeo.com https://*.vimeocdn.com \
           https://www.youtube.com https://www.google.com https://www.gstatic.com; \
        style-src 'self' 'unsafe-hashes' 'unsafe-inline' https://*.alkemio.org https://*.alkemio.foundation https://cdn.jsdelivr.net \ 
          https://fonts.googleapis.com https://fonts.gstatic.com https://*.netlify.app; \
        form-action 'self' https://*.hsforms.com; \
        script-src 'self' 'unsafe-hashes' 'unsafe-inline' 'unsafe-eval' https://*.netlify.com https://*.hs-scripts.com https://*.hscollectedforms.net \
          https://*.hs-analytics.net https://*.hs-banner.com https://*.hsforms.net https://platform.twitter.com https://player.vimeo.com \
          https://unpkg.com https://api.segment.io
          https://cdn.jsdelivr.net https://*.netlify.app https://www.google.com https://www.gstatic.com; \
        connect-src 'self' https://cdn.segment.com https://*.hs-banner.com https://*.hubspot.com https://*.hsforms.com https://www.netlifystatus.com \
          https://hubspot-forms-static-embed-eu1.s3.amazonaws.com https://*.hscollectedforms.net https://fonts.gstatic.com https://cdn.segment.com; \
        img-src 'self' https://*.hsforms.com blob: data: https:; \
        base-uri 'self'; \
        report-uri https://alkemio.report-uri.com/r/d/csp/enforce \
        """
