[build]
  command = "hugo --gc --minify -b $URL"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.101.0"
  HUGO_ENABLEGITINFO = "false"

[context.production.environment]
  HUGO_ENV = "production"

[context.deploy-preview]
  command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[[plugins]]
  package = "netlify-plugin-hugo-cache-resources"
  [plugins.inputs]
    debug = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Report-To = "{\"group\":\"default\",\"max_age\":31536000,\"endpoints\":[{\"url\":\"https://alkemio.report-uri.com/a/d/g\"}],\"include_subdomains\":true}"
    Content-Security-Policy = "default-src 'self' cdn.jsdelivr.net fonts.googleapis.com fonts.gstatic.com netlify.com *.netlify.com syndication.twitter.com platform.twitter.com *.hs-analytics.com *.hs-banner.com *.hs-scripts.com *.hscollectedforms.net *.hsforms.net *.hsforms.com *.vimeo.com vimeo.com *.vimeocdn.com www.youtube.com www.google.com www.gstatic.com; style-src 'self' 'unsafe-hashes' 'unsafe-inline' *.alkemio.foundation cdn.jsdelivr.net fonts.googleapis.com fonts.gstatic.com *.netlify.app; form-action 'self' *.hsforms.com; script-src 'self' 'unsafe-hashes' 'unsafe-inline' *.netlify.com *.hs-scripts.com *.hscollectedforms.net *.hs-analytics.net *.hs-banner.com *.hsforms.net platform.twitter.com player.vimeo.com cdn.jsdelivr.net *.netlify.app www.google.com www.gstatic.com; connect-src 'self' cdn.segment.com *.hs-banner.com *.hubspot.com *.hsforms.com hubspot-forms-static-embed-eu1.s3.amazonaws.com fonts.gstatic.com cdn.segment.com; img-src 'self' *.hsforms.com data: https:; base-uri 'self'; report-uri https://alkemio.report-uri.com/r/d/csp/enforce"
