[build]
  command = "hugo --gc --minify -b $URL"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.108.0"
  HUGO_ENABLEGITINFO = "false"
  GO_VERSION = "1.19"

[context.production.environment]
  HUGO_ENV = "production"

[context.deploy-preview]
  command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[[plugins]]
  package = "netlify-plugin-hugo-cache-resources"
  [plugins.inputs]
    debug = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Report-To = "{\"group\":\"default\",\"max_age\":31536000,\"endpoints\":[{\"url\":\"https://alkemio.report-uri.com/a/d/g\"}],\"include_subdomains\":true}"
    Content-Security-Policy = """
        default-src 'self' https://cdn.jsdelivr.net https://fonts.googleapis.com https://fonts.gstatic.com https://netlify.com https://*.netlify.com \
          https://syndication.twitter.com https://platform.twitter.com https://*.hs-analytics.com https://*.hs-banner.com https://*.hs-scripts.com \
          https://*.hscollectedforms.net https://*.hsforms.net https://*.hsforms.com https://*.vimeo.com https://vimeo.com https://*.vimeocdn.com \
           https://www.youtube.com https://www.google.com https://www.gstatic.com; \
        style-src 'self' 'unsafe-hashes' 'unsafe-inline' https://*.alkemio.org https://*.alkemio.foundation https://cdn.jsdelivr.net \ 
          https://fonts.googleapis.com https://fonts.gstatic.com https://*.netlify.app; \
        form-action 'self' https://*.hsforms.com; \
        script-src 'self' 'unsafe-hashes' 'unsafe-inline' 'unsafe-eval' https://*.netlify.com https://*.hs-scripts.com https://*.hscollectedforms.net \
          https://*.hs-analytics.net https://*.hs-banner.com https://*.hsforms.net https://platform.twitter.com https://player.vimeo.com \
          https://unpkg.com https://api.segment.io
          https://cdn.jsdelivr.net https://*.netlify.app https://www.google.com https://www.gstatic.com; \
        connect-src 'self' https://cdn.segment.com https://*.hs-banner.com https://*.hubspot.com https://*.hsforms.com \
          https://hubspot-forms-static-embed-eu1.s3.amazonaws.com https://*.hscollectedforms.net https://fonts.gstatic.com https://cdn.segment.com; \
        img-src 'self' https://*.hsforms.com data: https:; base-uri 'self'; \
        report-uri https://alkemio.report-uri.com/r/d/csp/enforce \
        """